// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonComp: typeof import('./src/components/Button/ButtonComp.vue')['default']
    Game: typeof import('./src/components/Game/Game.vue')['default']
    Key: typeof import('./src/components/Key/Key.vue')['default']
    Keyboard: typeof import('./src/components/Keyboard/Keyboard.vue')['default']
    Letter: typeof import('./src/components/Letter/Letter.vue')['default']
    Word: typeof import('./src/components/Word/Word.vue')['default']
  }
}

export {}
